const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process')
const root=path.resolve(__dirname,'..'),flush=()=>new Promise(r=>setImmediate(r))
function mount(name,old=false){
 const file='src/views/teaching/modules/'+name+'.vue',source=old?cp.execFileSync('git',['show','2a530a517d9eaaea5b4aa53a2f494edf521e4996:web/'+file],{cwd:root,encoding:'utf8'}):fs.readFileSync(path.join(root,file),'utf8')
 const calls=[],events=[],notices=[],confirms=[],ticks=[],callbacks=[],values={}
 const form={resetFields(){for(const k of Object.keys(values))delete values[k];this.touched=false},setFieldsValue(v){Object.assign(values,v)},isFieldsTouched(){return !!this.touched},validateFields(cb){callbacks.push(cb)}}
 const ctx={component:null,CourseFormRecovery:null,console:{log(){}},JUpload:{},JEditor:{},JDictSelectTag:{},TeachingMapEditor:{},JSelectDepart:{},pick:(o,...keys)=>Object.fromEntries(keys.filter(k=>k in o).map(k=>[k,o[k]])),getAction:()=>Promise.resolve({success:true,result:{records:[]}}),httpAction:(url,data,method)=>new Promise((resolve,reject)=>calls.push({url,data,method,resolve,reject}))}
 vm.createContext(ctx)
 if(!old)vm.runInContext(fs.readFileSync(path.join(root,'src/mixins/CourseFormRecovery.js'),'utf8').replace(/^import .*$/gm,'').replace('export default','CourseFormRecovery ='),ctx)
 vm.runInContext(source.match(/<script>([\s\S]*?)<\/script>/)[1].replace(/^\s*import .*$/gm,'').replace('export default','component ='),ctx)
 const c=ctx.component,m=ctx.CourseFormRecovery,i={...m?.data(),...c.data.call({$form:{createForm:()=>form}}),$refs:{},$set:(o,k,v)=>o[k]=v,$nextTick:cb=>ticks.push(cb),$emit:(...x)=>events.push(x),$message:{success:x=>notices.push(x),warning:x=>notices.push(x)},$confirm:x=>confirms.push(x)}
 for(const [k,v]of Object.entries({...m?.methods,...c.methods}))i[k]=v.bind(i)
 for(const [key,getter] of Object.entries(m?.computed||{}))Object.defineProperty(i,key,{get:()=>getter.call(i)})
 const ready=(record={id:'existing',courseName:'旧课程',unitName:'旧单元',courseId:'course',showCourseVideo:false,isShared:false})=>{i.edit(record);while(ticks.length)ticks.shift()()}
 return {i,m,calls,events,notices,confirms,ticks,callbacks,values,form,ready,validate:(error=null)=>callbacks.shift()(error,{...values})}
}
for(const name of ['TeachingCourseModal','TeachingCourseUnitModal']){
 test(name+' baseline: rejection closes old dialog; duplicate clicks send twice',async()=>{const h=mount(name,true);h.ready();h.i.handleOk();h.validate();h.i.handleOk();h.validate();assert.equal(h.calls.length,2);h.calls.forEach(c=>c.resolve({success:false,message:'reject'}));await flush();assert.equal(h.i.visible,false)})
 test(name+' locks validation, writes, closing and switching until success',async()=>{const h=mount(name);h.ready();h.values.courseName='修改';h.i.handleOk();h.i.handleOk();h.i.handleCancel();h.i.edit({id:'other'});assert.equal(h.callbacks.length,1);assert.equal(h.i.model.id,'existing');h.validate();h.i.handleOk();h.i.close();assert.equal(h.calls.length,1);assert.equal(h.i.visible,true);assert.equal(h.calls[0].data.courseName,'修改');assert.equal(h.i.model.courseName,'旧课程');assert.equal(h.calls[0].method,'put');h.calls[0].resolve({success:true});await flush();assert.equal(h.i.visible,false);assert.equal(h.i.confirmLoading,false);assert.equal(h.events.filter(x=>x[0]==='ok').length,1);assert.equal(h.notices.length,1)})
 test(name+' business failure retains fields and false switches; manual retry succeeds',async()=>{const h=mount(name);h.ready();h.values.courseName='保留';h.values.unitIntro='内容';h.values.courseVideo='file/key';h.i.model.isShared=true;h.i.handleOk();h.validate();h.calls[0].resolve({success:false,message:'SQL secret'});await flush();assert.equal(h.i.visible,true);assert.equal(h.values.unitIntro,'内容');assert.equal(h.i.model.isShared,true);assert.equal(h.i.confirmLoading,false);assert.doesNotMatch(h.i.saveError,/SQL/);assert.equal(h.events.length,0);h.i.handleOk();h.validate();assert.equal(h.calls[1].data.courseVideo,'file/key');assert.equal(h.calls[1].data.showCourseVideo,false);h.calls[1].resolve({success:true});await flush();assert.equal(h.notices.length,1)})
 test(name+' network error preserves new input and warns of uncertain creation; no automatic retry',async()=>{const h=mount(name);h.ready({});h.values.courseName='新建';h.i.handleOk();h.validate();assert.equal(h.calls[0].method,'post');h.calls[0].reject(new Error('lost'));await flush();assert.equal(h.i.visible,true);assert.equal(h.values.courseName,'新建');assert.equal(h.i.confirmLoading,false);assert.match(h.i.saveError,/核对列表/);assert.equal(h.calls.length,1);assert.equal(h.events.length,0)})
 test(name+' validation failure unlocks without request',()=>{const h=mount(name);h.ready();h.i.handleOk();h.validate({name:'invalid'});assert.equal(h.calls.length,0);assert.equal(h.i.confirmLoading,false);assert.equal(h.i.visible,true)})
 test(name+' malformed success cannot close or report success',async()=>{for(const result of [null,{}, {success:'true'}]){const h=mount(name);h.ready();h.i.handleOk();h.validate();h.calls[0].resolve(result);await flush();assert.equal(h.i.visible,true);assert.ok(h.i.saveError);assert.equal(h.notices.length,0)}})
 test(name+' dirty cancel supports continuing, prevents stacked prompts, clean cancel closes',()=>{const h=mount(name);h.ready();h.form.touched=true;h.i.handleCancel();h.i.handleCancel();h.i.handleOk();assert.equal(h.confirms.length,1);assert.equal(h.callbacks.length,0);h.confirms[0].onCancel();assert.equal(h.i.visible,true);h.i.handleCancel();h.confirms[1].onOk();assert.equal(h.i.visible,false);h.ready();h.i.handleCancel();assert.equal(h.i.visible,false);assert.equal(h.confirms.length,2)})
 test(name+' switch-only change is dirty; stale confirmation cannot close another record',()=>{const h=mount(name);h.ready();h.i.model.isShared=true;h.i.handleCancel();assert.equal(h.confirms.length,1);h.ready({id:'next'});h.confirms[0].onOk();assert.equal(h.i.visible,true);assert.equal(h.i.model.id,'next')})
 test(name+' delayed nextTick cannot populate newer or closed dialog',()=>{const h=mount(name);const key=name==='TeachingCourseModal'?'courseName':'unitName';h.i.edit({id:'old',[key]:'旧'});h.i.edit({id:'new',[key]:'新'});h.ticks.reverse().forEach(fn=>fn());assert.equal(h.values[key],'新');h.i.edit({id:'closed',[key]:'关闭'});h.i.close();h.ticks.at(-1)();assert.equal(h.values[key],undefined)})
 test(name+' destroyed dialog ignores validation and save response',async()=>{const h=mount(name);h.ready();h.i.handleOk();h.m.beforeDestroy.call(h.i);h.validate();assert.equal(h.calls.length,0);const b=mount(name);b.ready();b.i.handleOk();b.validate();b.m.beforeDestroy.call(b.i);b.calls[0].resolve({success:true});await flush();assert.equal(b.events.length,0);assert.equal(b.notices.length,0)})
}
