const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),crypto=require('node:crypto'),{execFileSync}=require('node:child_process')
const {create,endpoint}=require('../public/scratch3/cloud-client.js')
function harness({seed=false,token='token-a',empty=false}={}) {
 const h={token,sockets:[],states:[],posts:[],timers:new Map(),sequence:0,variables:empty?{}:{score:{name:'score',value:3,isCloud:true}}}
 class Socket {
  constructor(url){this.url=url;this.readyState=0;this.sent=[];h.sockets.push(this)}
  send(raw){this.sent.push(JSON.parse(raw))}
  close(){this.readyState=3;this.closed=true}
  open(){this.readyState=1;this.onopen()}
  message(data){this.onmessage({data:typeof data==='string'?data:JSON.stringify(data)+'\n'})}
  ack(name=null,reply='OK'){this.message({method:'ack',name,reply})}
  finish(code=1006){this.readyState=3;this.onclose({code})}
 }
 h.vm={runtime:{hasCloudData:()=>Object.values(h.variables).some(v=>v.isCloud),getTargetForStage:()=>({variables:h.variables})},setCloudProvider:p=>h.provider=p,postIOData:(device,data)=>{h.posts.push({device,data});Object.values(h.variables).find(v=>v.name===data.varUpdate.name).value=data.varUpdate.value}}
 h.client=create({vm:h.vm,WebSocket:Socket,origin:'http://127.0.0.1:18132',getToken:()=>h.token,seed,onStatus:s=>h.states.push(s),setTimeout:(fn,ms)=>{const id=++h.sequence;h.timers.set(id,{fn,ms});return id},clearTimeout:id=>h.timers.delete(id)})
 h.state=()=>h.states.at(-1);h.connect=(id='saved')=>{h.client.bind(id);const ws=h.sockets.at(-1);ws.open();ws.ack();return ws};h.run=ms=>{const found=[...h.timers].find(([,v])=>v.ms===ms);assert.ok(found,'timer '+ms);h.timers.delete(found[0]);found[1].fn()};return h
}
test('端点保留端口并跟随 HTTPS，拒绝其他协议',()=>{assert.equal(endpoint('http://127.0.0.1:18132'),'ws://127.0.0.1:18132/api/websocket/scratch/cloudData');assert.equal(endpoint('https://school.example'),'wss://school.example/api/websocket/scratch/cloudData');assert.throws(()=>endpoint('file:///tmp'))})
test('基线实际页面丢端口、共用 create、案例 URL 当项目；补丁只增加 opt-in guard',()=>{
 const old=execFileSync('git',['show','292dd7e:web/public/scratch3/index.html'],{encoding:'utf8'});assert.match(old,/location.hostname/);assert.match(old,/id: "create"/)
 const player=execFileSync('git',['show','292dd7e:web/public/scratch3/player.html'],{encoding:'utf8'});assert.match(player,/setCloudId\(workUrl\)/)
 const before=execFileSync('git',['show','292dd7e:web/public/scratch3/lib.min.js'],{maxBuffer:20*1024*1024}),patch=require('./scratch-cloud-vendor-patch.json'),after=fs.readFileSync(require.resolve('../public/scratch3/lib.min.js'))
 assert.equal(crypto.createHash('sha256').update(before).digest('hex'),patch.before_sha256);assert.equal(before.toString().split(patch.find).length-1,1);assert.equal(before.toString().replace(patch.find,patch.replace),after.toString());assert.equal(crypto.createHash('sha256').update(after).digest('hex'),patch.after_sha256)
})
test('未保存、URL、非法作品无连接，变量值保留本地',()=>{for(const id of ['', 'create','https://a/project.sb3','a'.repeat(65)]){const h=harness();h.client.bind(id);h.client.updateVariable('score',9);assert.equal(h.sockets.length,0);assert.equal(h.variables.score.value,3);assert.equal(h.state().phase,'local')}})
test('无变量不建立连接，保存后新建云变量可启动连接',()=>{const h=harness({empty:true,seed:true});h.client.bind('saved');assert.equal(h.sockets.length,0);h.variables.score={name:'score',value:4,isCloud:true};h.client.createVariable('score',4);assert.equal(h.sockets.length,1);h.sockets[0].open();h.sockets[0].ack();assert.equal(h.sockets[0].sent[1].method,'create')})
test('先握手再修改，正确带身份且 URL 不携带令牌',()=>{const h=harness(),ws=h.connect();assert.equal(ws.url.includes('token'),false);assert.deepEqual(ws.sent[0],{project_id:'saved',token:'token-a',method:'handshake'});h.client.updateVariable('score',10);assert.equal(ws.sent[1].method,'set');assert.equal(ws.sent[1].value,'10')})
test('快照在完成确认前应用，只创建作者缺少的变量，不覆盖已有值',()=>{const h=harness({seed:true});h.variables.next={name:'next',value:6,isCloud:true};h.client.bind('saved');const ws=h.sockets[0];ws.open();ws.message({method:'set',project_id:'saved',name:'score',value:'99'});assert.equal(h.variables.score.value,'99');assert.equal(ws.sent.length,1);ws.ack();assert.equal(ws.sent[1].method,'create');assert.equal(ws.sent[1].name,'next');ws.ack('next');assert.equal(ws.sent.length,2)})
test('匿名只读可接收值，不能发送写入或播种',()=>{const h=harness({seed:true,token:''}),ws=h.connect();h.client.updateVariable('score',9);assert.equal(ws.sent.length,1);ws.message({method:'set',project_id:'saved',name:'score',value:'8'});assert.equal(h.variables.score.value,'8');assert.equal(h.state().phase,'readonly')})
test('修改串行确认，拒绝可见但继续接收更新',()=>{const h=harness(),ws=h.connect();h.client.updateVariable('score',1);h.client.renameVariable('score','next');assert.equal(ws.sent.length,2);ws.ack('score','FAIL');assert.equal(h.state().phase,'error');assert.equal(ws.sent[2].method,'rename');ws.ack('score');ws.message({method:'set',project_id:'saved',name:'score',value:'8'});assert.equal(h.variables.score.value,'8')})
test('同作品重复 bind 不重复连接，切换关闭旧连接且丢弃旧回调',()=>{const h=harness(),ws=h.connect(),old=ws.onmessage;h.client.bind('saved');assert.equal(h.sockets.length,1);h.client.bind('other');assert.equal(ws.closed,true);old({data:JSON.stringify({method:'set',project_id:'saved',name:'score',value:'old'})});assert.equal(h.posts.length,0);assert.equal(h.sockets.length,2)})
test('会话变化关闭连接并停止重连，明确重试才使用新身份',()=>{const h=harness(),ws=h.connect();h.token='token-b';assert.equal(h.client.checkSession(),false);assert.equal(ws.closed,true);assert.equal(h.state().phase,'session');assert.equal(h.timers.size,0);h.client.retry();h.sockets[1].open();assert.equal(h.sockets[1].sent[0].token,'token-b')})
test('收发前也检查会话，不能在轮询间隙使用旧身份',()=>{for(const operation of ['write','read']){const h=harness(),ws=h.connect();h.token='';if(operation==='write')h.client.updateVariable('score',9);else ws.message({method:'set',project_id:'saved',name:'score',value:'9'});assert.equal(ws.closed,true);assert.equal(ws.sent.length,1);assert.equal(h.posts.length,0)}})
test('策略拒绝和过大消息不自动重连',()=>{for(const code of [1008,1009]){const h=harness(),ws=h.connect();ws.finish(code);assert.equal(h.state().phase,'denied');assert.equal(h.timers.size,0);assert.equal(h.sockets.length,1)}})
test('网络断开后有限退避，不补发未确认与排队写入',()=>{const h=harness(),ws=h.connect();h.client.updateVariable('score',10);h.client.updateVariable('score',11);ws.finish();h.run(500);const next=h.sockets[1];next.open();next.ack();assert.equal(next.sent.length,1);assert.equal(h.state().phase,'ready')})
test('连续连接失败最多五次自动重试，然后手动恢复',()=>{const h=harness();h.client.bind('saved');for(const delay of [500,1000,2000,4000,8000]){h.sockets.at(-1).finish();h.run(delay)}h.sockets.at(-1).finish();assert.equal(h.sockets.length,6);assert.equal(h.state().phase,'offline');assert.equal(h.timers.size,0);h.client.retry();assert.equal(h.sockets.length,7)})
test('握手与未确认修改有超时，不永久假连通',()=>{const h=harness();h.client.bind('saved');h.run(8000);assert.equal(h.sockets[0].closed,true);h.run(500);h.sockets[1].open();h.sockets[1].ack();h.client.updateVariable('score',9);h.run(8000);assert.equal(h.state().phase,'offline')})
test('非法响应、跨项目及错序确认停止同步，未知变量不注入 VM',()=>{for(const data of ['{bad',{method:'set',project_id:'other',name:'score',value:1},{method:'ack',name:'unsolicited',reply:'OK'}]){const h=harness(),ws=h.connect();ws.message(data);assert.equal(ws.closed,true);assert.equal(h.state().phase,'error')}const h=harness(),ws=h.connect();ws.message({method:'set',project_id:'saved',name:'unknown',value:'1'});assert.equal(h.posts.length,0)})
test('非法值不发送，队列上限触发明确停止而非无限积压',()=>{const h=harness(),ws=h.connect();for(const [n,v] of [['',1],['x'.repeat(129),1],['score',{}],['score','x'.repeat(1025)],['score',Infinity]])assert.equal(h.client.updateVariable(n,v),false);assert.equal(ws.sent.length,1);for(let i=0;i<66;i++)h.client.updateVariable('score',i);assert.equal(ws.closed,true);assert.match(h.state().message,/频繁/)})
test('VM 清理停止全部计时，重新打开作品可重新绑定',()=>{const h=harness(),ws=h.connect();h.client.requestCloseConnection();assert.equal(ws.closed,true);assert.equal(h.timers.size,0);h.client.bind('saved');assert.equal(h.sockets.length,2);h.client.destroy();h.client.bind('other');assert.equal(h.sockets.length,2)})
test('bfcache 暂停关闭连接，恢复重读；期间换身份不自动连接',()=>{const h=harness(),ws=h.connect();h.client.pause();assert.equal(ws.closed,true);h.client.resume();assert.equal(h.sockets.length,2);h.client.pause();h.token='new';h.client.resume();assert.equal(h.sockets.length,2);assert.equal(h.state().phase,'session')})
