const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs')
async function harness(params={},failure={}){
 const h={token:'fixture-token',requests:[],binds:[],closed:0,starts:0,loads:[],nodes:{'player-status':{},'retry-project':{}}};const engine={stopAll(){},loadProject:async bytes=>{if(failure.engine)throw Error('invalid archive');h.loads.push(bytes)},runtime:{start:()=>h.starts++}}
 const context={URL,AbortController,setTimeout,clearTimeout,Promise,document:{getElementById:id=>h.nodes[id]},urlParams:n=>params[n]||'',getUserToken:()=>h.token,location:{href:'http://127.0.0.1:18133/scratch3/player.html'},TeachingScratchCloud:{mount:()=>({bind:id=>h.binds.push(id),requestCloseConnection:()=>h.closed++})},fetch:async(url,options)=>{h.requests.push({url,options});if(failure.delay)await failure.delay();const binary=!url.startsWith('/api');return {ok:!failure.status,status:failure.status||200,json:async()=>failure.bad?{success:false}:{success:true,result:{workFileKey_url:'/api/sys/common/static/fixture/a.sb3'}},arrayBuffer:async()=>new Uint8Array([80,75]).buffer}}}
 context.window=context;vm.runInNewContext(fs.readFileSync(require.resolve('../public/scratch3/player-bridge.js'),'utf8'),context);context.TeachingScratchPlayer.initialize(engine);h.start=context.TeachingScratchPlayer.start;return h
}
test('播放器详情使用当前身份，附件请求不携带 JWT；成功打开才连接真实作品',async()=>{const h=await harness({workId:'saved'});await h.start();assert.equal(h.requests[0].options.headers['X-Access-Token'],'fixture-token');assert.equal(Object.keys(h.requests[1].options.headers).length,0);assert.deepEqual(h.binds,['saved']);assert.equal(h.loads.length,1);assert.equal(h.starts,1)})
test('案例 URL 仅本机云状态，不用地址或同时给出的 workId 绑定云端',async()=>{const h=await harness({workUrl:'/sample.sb3',workId:'ignored'});await h.start();assert.equal(h.requests.length,1);assert.equal(h.binds.length,0);assert.equal(h.starts,1)})
test('无作品和非法地址不连接、不执行项目',async()=>{for(const params of [{},{workUrl:'javascript:alert(1)'}]){const h=await harness(params);await h.start();assert.equal(h.requests.length,0);assert.equal(h.binds.length,0);assert.equal(h.starts,0)}})
test('403、业务失败和项目格式错误都有重试入口，不假报连接',async()=>{for(const f of [{status:403},{bad:true},{engine:true}]){const h=await harness({workId:'saved'},f);await h.start();assert.equal(h.nodes['retry-project'].hidden,false);assert.ok(h.nodes['player-status'].textContent);assert.equal(h.binds.length,0);assert.equal(h.starts,0)}})
test('读取过程中身份变化不运行旧会话作品',async()=>{let release;const h=await harness({workId:'saved'},{delay:()=>new Promise(r=>release=r)});const load=h.start();await Promise.resolve();h.token='new';release();await new Promise(r=>setImmediate(r));release();await load;assert.equal(h.loads.length,0);assert.equal(h.binds.length,0);assert.match(h.nodes['player-status'].textContent,/登录状态/)} )
